from . import account_invoice
from . import custom_fields
from . import crm_lead
from . import hr_employee
from . import purchase_order
from . import sale_order
from . import mrp_production
from . import res_company
from . import res_partner
