from . import account_discount_line
from . import account_invoice
from . import account_invoice_quantity_discount
from . import account_invoice_special_discount
from . import account_invoice_trade_discount
from . import product_template
from . import sale_discount_line
from . import sale_order
from . import sales_discount